% Dominio numérico
int(0). int(1). int(2). int(3).

% Lentes
lente(l1). lente(l2). lente(l3).

% Aritmética (solo combinaciones necesarias)
pred(0,1). pred(1,2). pred(2,3).
suma(0,1,1). suma(1,1,2). suma(0,2,2).  % C <= 2
suma(1,2,3).  % Útil si N=1 y C=2 (pero la restricción C<=2 lo controla)

% Comparaciones
less(0,1). less(0,2). less(0,3).
less(1,2). less(1,3).
less(2,3).
menor_que(X,Y) :- less(X,Y).